### ISSUE TITLE
the ai is falling in loop if it is not getting or recognizing input

### ISSUE THREAD

**Issue by Gupta9934** [Gupta9934/AI-Voice-Assistant#4]
def takecommand():
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Listening.....")
        r.pause_threshold = 1 # wait for 1 sec before it start listening
        audio = r.listen(source) # it can access the microphone
    
    try:
        print("Recognizing.....")
        query = r.recognize_google(audio,'en=IN')
        print(query)
        
    except Exception as e:
        print(e)
        speak("unable to recognize your voice, Please Say that again.... ")
        
        return "None"
    
    return query

**Comment by sanjeebtiwary** [comment]
All good on the code
